local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, {})
vim.keymap.set('n', '<leader>pr', builtin.resume, {})
vim.keymap.set('n', '<leader>ph', builtin.help_tags, {})
vim.keymap.set('n', '<leader>hi', builtin.highlights, {})
vim.keymap.set('n', '<leader>gd',  builtin.lsp_implementations, {})
vim.keymap.set('n', '<leader>gD',  builtin.lsp_definitions, {})
vim.keymap.set('n', '<leader>gt',  builtin.lsp_type_definitions, {})
vim.keymap.set('n', '<leader>pb', builtin.buffers, {})
vim.keymap.set('n', '<leader>vi', builtin.vim_options, {})
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
vim.keymap.set('n', '<leader>ps', function()
	builtin.grep_string({search = vim.fn.input("Grep > ")});
end)
